spring.application.name=taskflow-backend

spring.datasource.url=jdbc:postgresql://ep-wispy-mud-aw71qffw-pooler.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HfU7jWK9GQhm

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SERVER PORT
server.port=${PORT:8080}
server.address=0.0.0.0